apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: route-frontend
  name: frontend
  namespace: mysql
spec:
  host: database.apps.ocp4-mng.example.com
  path: "/todo"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: prod-frontend
    weight: 100
  wildcardPolicy: None
